openapi: 3.0.3
info:
  title: Basic Auth Example
  version: "1.0"
servers:
  - url: /openapi
paths:
  /secret:
    get:
      summary: Return secret string
      operationId: app.get_secret
      responses:
        "200":
          description: secret response
          content:
            "*/*":
              schema:
                type: string
      security:
        - basic: []
  /health:
    get:
      summary: Return secret string
      operationId: services.healthcheck.ping
      responses:
        "200":
          description: secret response
          content:
            "*/*":
              schema:
                type: string
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: app.basic_auth
